spring:
  profiles:
    active: local # default
    group:
      local:
        - common
      prod:
        - common
---

spring:
  config:
    activate:
      on-profile: common

kakao:
  rest:
    api:
      key: ${KAKAO_REST_API_KEY}

# ...

---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/pharmacy_recommendation
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  redis:
    host: localhost
    port: 6379
  jpa:
#    database: mariadb   # 추가 해준 부분
    database-platform: org.hibernate.dialect.MariaDB103Dialect # 추가 해준 부분
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
---

spring:
  config:
    activate:
      on-profile: prod

---

